on: [push]
name: Build ThinBridge
jobs:
  build:
    runs-on: [ windows-2019 ]
    steps:
      - uses: actions/checkout@v2
      - uses: microsoft/setup-msbuild@v1.0.2
      - name: Compile x86
        run: msbuild /p:Platform=Win32 /p:Configuration=Release
      - name: Compile x64
        run: |
          msbuild /p:Configuration=Release /p:"Platform=x64;OutDir=$pwd\x64\"
          copy x64\ThinBridgeBHO64.dll Release
      - name: Make Installer (x86)
        run: iscc.exe ThinBridgeX86.iss
      - name: Make Installer (x64)
        run: iscc.exe ThinBridgeX64.iss
      - name: Upload Binaries
        uses: actions/upload-artifact@v2
        with:
          name: Binaries
          path: |
            Release/*.exe
            Release/*.dll
      - name: Upload Installer
        uses: actions/upload-artifact@v2
        with:
          name: Installers
          path: SetupOutput/*.exe
  webextension:
    runs-on: [ ubuntu-latest ]
    steps:
      - uses: actions/checkout@v2
      - name: Build Testing Extensions
        run: |
          cp webextension/edge/manifest.json.dev webextension/edge/manifest.json
          make -C webextension/edge
          cp webextension/chrome/manifest.json.dev webextension/chrome/manifest.json
          make -C webextension/chrome
          make -C webextension/firefox
      - name: Upload Extensions
        uses: actions/upload-artifact@v2
        with:
          name: WebExtensions
          path: webextension/*/*.zip
